# Generated by Django 4.2.11 on 2024-04-05 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("weblog", "0002_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comments_Weblog",
        ),
    ]
