# Generated by Django 4.2.11 on 2024-04-05 13:17

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0003_rename_comments_comments_weblog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags_Weblog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        max_length=100, verbose_name="تگ برای پست های وبلاگ"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="آدرس اینترنتی برای تگ پست")),
            ],
            options={
                "verbose_name_plural": "تگ های پست های وبسایت",
                "db_table": "Tags_Weblog",
            },
        ),
        migrations.AlterModelOptions(
            name="comments_weblog",
            options={"ordering": ["-id"], "verbose_name_plural": "کامنت پست ها"},
        ),
        migrations.AlterField(
            model_name="post_weblog",
            name="creation",
            field=django_jalali.db.models.jDateTimeField(
                verbose_name="انتخاب زمان ساخت"
            ),
        ),
        migrations.AddField(
            model_name="post_weblog",
            name="tags",
            field=models.ManyToManyField(
                help_text="بیش از یکی هم میتوان انتخاب نمود",
                related_name="post_weblog",
                to="weblog.tags_weblog",
                verbose_name="تگ پست های وبسایت",
            ),
        ),
    ]
