# Generated by Django 4.2.11 on 2024-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0004_tags_weblog_alter_comments_weblog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags_weblog",
            name="slug",
            field=models.SlugField(
                unique=True, verbose_name="آدرس اینترنتی برای تگ پست"
            ),
        ),
    ]
