# Generated by Django 4.2.11 on 2024-04-07 07:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="دسته بندی محصولات"),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True, verbose_name="آدرس اینترنتی دسته بندی محصولات"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "دسته بندی محصولات",
                "db_table": "Category_Product",
            },
        ),
        migrations.CreateModel(
            name="Tag_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="تگ محصولات")),
                (
                    "slug",
                    models.SlugField(
                        unique=True, verbose_name="آدرس اینترنتی تگ محصولات"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "تگ های محصولات",
                "db_table": "Tag_Product",
            },
        ),
        migrations.CreateModel(
            name="Product_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture1",
                    models.FileField(
                        upload_to="Product/%Y/%m/%d", verbose_name="تصویر1"
                    ),
                ),
                (
                    "picture2",
                    models.FileField(
                        upload_to="Product/%Y/%m/%d", verbose_name="تصویر2"
                    ),
                ),
                (
                    "picture3",
                    models.FileField(
                        upload_to="Product/%Y/%m/%d", verbose_name="تصویر3"
                    ),
                ),
                (
                    "picture4",
                    models.FileField(
                        upload_to="Product/%Y/%m/%d", verbose_name="تصویر4"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="نام محصول"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="به طور خودکار این فیلد مقدار دهی میشود",
                        unique=True,
                        verbose_name="آدرس اینترنتی محصول",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="توضیحات")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="میزان قیمت محصول"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="product.category_product",
                        verbose_name="دسته بندی محصول",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="products",
                        to="product.tag_product",
                        verbose_name="تگ های محصولات",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "مشخصات محصولات",
                "db_table": "Product_Product",
            },
        ),
    ]
