# Generated by Django 4.2.11 on 2024-04-09 21:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="نام دسته بندی دوره های وبسایت"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="آدرس اینترنتی وبسایت"),
                ),
            ],
            options={
                "verbose_name_plural": "دسته بندی های دوره های وبسایت",
                "db_table": "Course_Category",
            },
        ),
        migrations.CreateModel(
            name="Course_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=100, verbose_name="نام دوره"),
                ),
                (
                    "course_description",
                    ckeditor.fields.RichTextField(verbose_name="توضیحات دوره"),
                ),
                (
                    "learning",
                    ckeditor.fields.RichTextField(verbose_name="آنچه یادمیگیرید"),
                ),
                (
                    "requirements",
                    ckeditor.fields.RichTextField(verbose_name="پیش نیاز های دوره"),
                ),
                ("teacher_description", models.TextField(verbose_name="توضیحات مدرس")),
                (
                    "video",
                    models.FileField(
                        upload_to="Course_Information/<django.db.models.fields.CharField>/%y/%m/%d",
                        verbose_name="ویدیو مقدمه انتشار دوره",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت دوره"
                    ),
                ),
                ("level", models.CharField(max_length=100, verbose_name="سطح دوره")),
                (
                    "languages",
                    models.CharField(max_length=100, verbose_name="زبان دوره"),
                ),
                (
                    "exam",
                    models.BooleanField(default=False, verbose_name="امتحان دارد"),
                ),
                ("duration", models.IntegerField(default=35, verbose_name="مدت دوره")),
                (
                    "certificated",
                    models.BooleanField(default=False, verbose_name="آیا مدرک دارد"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course_category",
                        verbose_name="نام دسته بندی",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_information",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدرس",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "دوره های وبسایت",
                "db_table": "Course_Information",
            },
        ),
    ]
