# Generated by Django 4.2.11 on 2024-04-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_information",
            name="picture",
            field=models.FileField(
                null=True,
                upload_to="Course_Information/<django.db.models.fields.CharField>/%y/%m/%d",
                verbose_name="عکس اول",
            ),
        ),
    ]
