# Generated by Django 4.2.11 on 2024-04-10 10:50

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_information_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course_Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام تگ")),
                (
                    "slug",
                    models.SlugField(
                        help_text="فیلد به طور خودکار مقدار دهی میشود",
                        unique=True,
                        verbose_name="آدرس اینترنتی تگ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "تگ های دوره های وبسایت",
                "db_table": "Course_Tag",
            },
        ),
        migrations.AddField(
            model_name="course_information",
            name="intoduce_centense",
            field=models.CharField(
                max_length=100, null=True, verbose_name="توضیح خیلی مختصر"
            ),
        ),
        migrations.AddField(
            model_name="course_information",
            name="time",
            field=django_jalali.db.models.jDateTimeField(
                default=django.utils.timezone.now, null=True, verbose_name="زمان ساخت"
            ),
        ),
        migrations.AddField(
            model_name="course_information",
            name="update",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="زمان آپدیت"
            ),
        ),
        migrations.AddField(
            model_name="course_information",
            name="tags",
            field=models.ManyToManyField(
                null=True, to="course.course_tag", verbose_name="تگ های دوره های وبسایت"
            ),
        ),
    ]
