# Generated by Django 4.2.11 on 2024-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_tag_course_information_intoduce_centense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_tag",
            name="color",
            field=models.CharField(
                choices=[("red", "قرمز"), ("white", "سفید"), ("dark-1", "مشکی")],
                default="red",
                max_length=100,
                verbose_name="رنگ",
            ),
        ),
    ]
