# Generated by Django 4.2.11 on 2024-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_course_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-red-1", "قرمز"),
                    ("bg-white-1", "سفید"),
                    ("bg-dark-1", "مشکی"),
                ],
                default="red",
                max_length=100,
                verbose_name="رنگ",
            ),
        ),
    ]
