# Generated by Django 4.2.11 on 2024-04-10 11:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_course_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_information",
            name="teacher_description_about_course",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="توضیحات مدرس درباره دوره"
            ),
        ),
        migrations.AlterField(
            model_name="course_information",
            name="teacher_description",
            field=ckeditor.fields.RichTextField(verbose_name="توضیحات درباره مدرس "),
        ),
    ]
