# Generated by Django 4.2.11 on 2024-04-10 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0006_course_information_teacher_description_about_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course_Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("text", models.TextField(verbose_name="متن کامنت برای دوره")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_comments",
                        to="course.course_information",
                        verbose_name="دوره آموزشی",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "کامنت های دوره ها",
                "db_table": "Course_Comments",
            },
        ),
    ]
