# Generated by Django 4.2.11 on 2024-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="آیا کاربر فعال است ؟"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="آیا ادمین است ؟"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="نام و نام کاربری"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="otpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره تلفن"),
                ),
                ("code", models.PositiveSmallIntegerField(verbose_name="کد تایید")),
                (
                    "creation",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ساخت"),
                ),
            ],
        ),
    ]
