# Generated by Django 4.2.11 on 2024-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="User/%Y/%m/%d",
                verbose_name="تصویر کاربری",
            ),
        ),
    ]
