# Generated by Django 4.2.11 on 2024-04-09 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team_Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("introduce", models.CharField(verbose_name="معرفی نامه")),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="لینکدین"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="اینستاگرام"
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فرد",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "اعضای تیم",
                "db_table": "team_member",
            },
        ),
    ]
