# Generated by Django 4.2.11 on 2024-04-11 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_team_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="team_member",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="توضیحات درباره معرفی جامع عضو تیم"
            ),
        ),
    ]
