# Generated by Django 4.2.11 on 2024-04-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_team_member_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, verbose_name="نام مهارت")),
            ],
            options={
                "verbose_name_plural": "مهارت های اعضا",
                "db_table": "skills",
            },
        ),
        migrations.AddField(
            model_name="team_member",
            name="skills",
            field=models.ManyToManyField(null=True, to="accounts.skills"),
        ),
    ]
