# Generated by Django 4.2.11 on 2024-04-09 11:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.FileField(
                        upload_to="Event/Pictures/%Y/%m/%d",
                        verbose_name="تصویر سر تیتر برای سایت",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=100, verbose_name="نام رویداد را وارد کنید"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="محل برگزاری"),
                ),
                (
                    "time",
                    django_jalali.db.models.jDateTimeField(
                        verbose_name="تاریخ و زمان برگزاری"
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="متن")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت اصلی"
                    ),
                ),
                (
                    "off",
                    models.BooleanField(default=False, verbose_name="آیا تخفیف دارد"),
                ),
                (
                    "price2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="قیمت تخفیف خورده",
                    ),
                ),
                (
                    "Presentors",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="اراپه دهندگان"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "رویداد های وبسایت",
                "db_table": "Event_Information",
            },
        ),
    ]
