# Generated by Django 4.2.11 on 2024-04-09 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event_information",
            name="learning",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="آنچه یادمیگیرید"
            ),
        ),
        migrations.AddField(
            model_name="event_information",
            name="requirements",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="پیشنیازهای رویداد"
            ),
        ),
    ]
