# Generated by Django 4.2.11 on 2024-04-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Event", "0002_event_information_learning_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event_Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("text", models.TextField(verbose_name="متن کامنت برای رویداد")),
                (
                    "time",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="زمان"
                    ),
                ),
                (
                    "Person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments",
                        to="Event.event_information",
                        verbose_name="رویداد",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "کامنت های رویداد ها",
                "db_table": "Event_Comment",
                "ordering": ["-id"],
            },
        ),
    ]
